//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Green_Bus_Ticket_System_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubscription
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int SubscriptionId { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public bool IsActive { get; set; }
        public int TicketRemaining { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual User User { get; set; }
    }
}
