//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Green_Bus_Ticket_System_Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public string CardId { get; set; }
        public int TicketTypeId { get; set; }
        public int BusRouteId { get; set; }
        public int Total { get; set; }
    
        public virtual BusRoute BusRoute { get; set; }
        public virtual Card Card { get; set; }
        public virtual TicketType TicketType { get; set; }
    }
}
